#!/usr/bin/env python3
"""
================================================================================
✅ AI 友好示例 - 区域对比分析（Regional Comparison）
================================================================================

此示例已验证可直接运行，AI 可参考实现类似任务。

【AI 使用指南】
1. 这是一个完整的、可运行的示例
2. 展示了正确的 API 使用方式
3. 当用户需要"对比两个区域"时，直接复用此模板
4. 修改查询参数即可适应不同需求

【关键 API】
- handler.query(country_state=...)  # ⭐ 查询特定国家（注意：country_state 不是 countries）
- handler.clean(df, concordance_min=0.90)  # 数据清洗
- handler.ks_test(ages_a, ages_b)  # K-S 统计检验
- handler.plot_multi_kde({...})  # 多样品 KDE 对比图

【返回值注意】⭐ 重要
- ks_result['statistic']  # ✅ 正确：D 统计量
- ks_result['d_statistic']  # ❌ 错误：这个键不存在！

【常见错误修正】
✓ 使用 'country_state' 而非 'countries'
✓ 列名是 'Best Age' 而非 'BestAge'
✓ 检查 df.height > 0 再处理数据
✓ 使用英文标签避免字体问题（如 {"China": ages} 而非 {"中国": ages}）

【适用场景】
- ✅ 对比两个/多个区域的锆石数据
- ✅ K-S 统计检验验证差异显著性
- ✅ 生成对比 KDE 图
- ✅ 用户询问"中国和澳大利亚对比"（最常见！）

【代码位置】
完整代码: assets/examples/regional_comparison.py
索引文件: assets/examples/examples_index.md

【修改模板】
如需对比其他区域，只需修改：
- df_china = handler.query(country_state="China") → 改为目标国家
- df_australia = handler.query(country_state="Australia") → 改为另一个国家
- 图表标签 {"China": ..., "Australia": ...} → 改为对应的英文标签

================================================================================

China and Australia Zircon Data Comparative Analysis
===================================================

Auto-generated by OneDZ Skill - English version to avoid font issues

Generated: 2026-04-20
Task: Query and compare zircon data from China and Australia
"""

import sys
from pathlib import Path
import polars as pl

# Import OneDZ Handler
from scripts.onedz_handler import OneDZHandler


def analyze_region(handler, region_name, country_code=None):
    """Analyze data from a single region"""
    print(f"\n{'='*70}")
    print(f"🌍 {region_name} Zircon Data Analysis")
    print(f"{'='*70}")

    # Query data
    if country_code:
        df = handler.query(country_state=country_code)
    else:
        df = handler.query(continent=region_name)

    if df.height == 0:
        print(f"⚠️  No data found for {region_name}")
        return None, None, None

    print(f"📊 Raw records: {df.height:,}")

    # Data cleaning
    df_clean = handler.clean(
        df,
        compute_best_age=True,
        filter_concordance=True,
        concordance_min=0.90,
        concordance_max=1.10,
        standardize_errors=True,
        target_sigma=1,
        remove_null_ages=True,
        age_range=(0, 4500)
    )

    cleaning_rate = df_clean.height / df.height * 100 if df.height > 0 else 0
    print(f"✅ Cleaned: {df_clean.height:,} records (Cleaning rate: {cleaning_rate:.1f}%)")

    # Statistical analysis
    result = handler.analyze(df_clean)
    summary = result["summary"]
    peaks = result["peaks"]

    print(f"\n📈 Basic Statistics:")
    print(f"   Sample size:     {summary['n']:,}")
    print(f"   Age range:       {summary['min']:.1f} - {summary['max']:.1f} Ma")
    print(f"   Mean age:        {summary['mean']:.1f} ± {summary['std']:.1f} Ma")
    print(f"   Median:          {summary['median']:.1f} Ma")

    if len(peaks) > 0:
        print(f"\n🏔️  Major peaks (top 5):")
        for i, peak in enumerate(peaks[:5], 1):
            print(f"   {i}. {peak['age']:.1f} ± {peak['uncertainty']:.1f} Ma")
    else:
        print(f"\n⚠️  No significant peaks detected")

    return df_clean, summary, peaks


def compare_distributions(summary_china, summary_australia):
    """Compare age distributions between two regions"""
    print(f"\n{'='*70}")
    print(f"📊 China vs Australia - Age Distribution Comparison")
    print(f"{'='*70}")

    print(f"\n{'Metric':<20} {'China':>20} {'Australia':>20}")
    print(f"{'-'*60}")
    print(f"{'Sample size':<20} {summary_china['n']:>20,} {summary_australia['n']:>20,}")
    print(f"{'Age range':<20} {summary_china['min']:>8.0f}-{summary_china['max']:>8.0f} Ma  {summary_australia['min']:>8.0f}-{summary_australia['max']:>8.0f} Ma")
    print(f"{'Mean age':<20} {summary_china['mean']:>20.1f} {summary_australia['mean']:>20.1f}")
    print(f"{'Std deviation':<20} {summary_china['std']:>20.1f} {summary_australia['std']:>20.1f}")
    print(f"{'Median':<20} {summary_china['median']:>20.1f} {summary_australia['median']:>20.1f}")


def main():
    print("=" * 70)
    print("Zircon Data Comparison: China vs Australia")
    print("   Auto-generated by OneDZ Skill")
    print("=" * 70)

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Step 1: Initialize
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    print("\n📦 [1/4] Initializing OneDZ Handler...")

    handler = OneDZHandler()
    handler.load(source="csv", table="global_u-pb")

    print(f"✅ Global data loaded: {handler.data.height:,} records")

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Step 2: Query and analyze China data
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    print("\n🇨🇳 [2/4] Querying China zircon data...")

    df_china, summary_china, peaks_china = analyze_region(
        handler,
        region_name="China",
        country_code="China"
    )

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Step 3: Query and analyze Australia data
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    print("\n🇦🇺 [3/4] Querying Australia zircon data...")

    df_australia, summary_australia, peaks_australia = analyze_region(
        handler,
        region_name="Australia",
        country_code="Australia"
    )

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Step 4: Comparative analysis and visualization
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    if df_china is not None and df_australia is not None:
        # Compare statistics
        compare_distributions(summary_china, summary_australia)

        # K-S test
        print(f"\n🧪 [4/4] Statistical testing...")
        ages_china = df_china["Best Age"].drop_nulls().to_numpy()
        ages_australia = df_australia["Best Age"].drop_nulls().to_numpy()

        ks_result = handler.ks_test(ages_china, ages_australia, alpha=0.05)
        print(f"\n   Kolmogorov-Smirnov Test:")
        print(f"   D-statistic: {ks_result['statistic']:.4f}")
        print(f"   p-value: {ks_result['p_value']:.4e}")
        print(f"   Conclusion: {ks_result['conclusion']}")

        # Visualization
        print(f"\n🎨 Generating visualizations...")

        # 1. China KDE plot
        handler.plot_age(
            df_china,
            mode="kde",
            age_range=(0, 4000),
            save="china_kde.png"
        )
        print(f"   ✅ China KDE: china_kde.png")

        # 2. Australia KDE plot
        handler.plot_age(
            df_australia,
            mode="kde",
            age_range=(0, 4000),
            save="australia_kde.png"
        )
        print(f"   ✅ Australia KDE: australia_kde.png")

        # 3. Comparison KDE plot (use English labels!)
        handler.plot_multi_kde(
            {"China": ages_china, "Australia": ages_australia},
            age_range=(0, 4000),
            save="china_australia_comparison.png"
        )
        print(f"   ✅ Comparison KDE: china_australia_comparison.png")

        # 4. Geographic distribution
        handler.viz.plot_geographic_distribution(
            df_china,
            geo_level="country",
            top_n=15,
            save="china_geo.png"
        )
        print(f"   ✅ China geographic: china_geo.png")

        handler.viz.plot_geographic_distribution(
            df_australia,
            geo_level="country",
            top_n=15,
            save="australia_geo.png"
        )
        print(f"   ✅ Australia geographic: australia_geo.png")

        # Export data
        print(f"\n💾 Exporting data...")
        handler.export(df_china, "china_data.csv")
        print(f"   ✅ China data: china_data.csv")

        handler.export(df_australia, "australia_data.csv")
        print(f"   ✅ Australia data: australia_data.csv")

        # Final summary
        print(f"\n{'='*70}")
        print(f"🎉 Analysis Complete!")
        print(f"{'='*70}")

        print(f"\n📁 Generated Files:")
        print(f"   • china_kde.png                    - China age distribution")
        print(f"   • australia_kde.png                - Australia age distribution")
        print(f"   • china_australia_comparison.png   - Comparison plot")
        print(f"   • china_geo.png                    - China geographic distribution")
        print(f"   • australia_geo.png                - Australia geographic distribution")
        print(f"   • china_data.csv                   - China data")
        print(f"   • australia_data.csv               - Australia data")

        print(f"\n📊 Key Findings:")
        print(f"   • China samples: {summary_china['n']:,}")
        print(f"   • Australia samples: {summary_australia['n']:,}")
        print(f"   • China median age: {summary_china['median']:.0f} Ma")
        print(f"   • Australia median age: {summary_australia['median']:.0f} Ma")

        age_diff = summary_china['median'] - summary_australia['median']
        print(f"   • Age difference: {abs(age_diff):.0f} Ma ({'China older' if age_diff > 0 else 'Australia older'})")

        print(f"\n💡 Note:")
        print(f"   This script uses English labels to avoid font rendering issues")
        print(f"   All plots display correctly without warnings")

    else:
        print("\n⚠️  Cannot complete comparison (missing data)")


if __name__ == "__main__":
    main()
